FROM  rocm/dev-ubuntu-22.04:6.2-complete

RUN --mount=type=cache,target=/root/.cache/pip \
   pip3 install pyopencl==2026.1.2 pillow==12.1.1 ImageIO==2.37.2 imageio-ffmpeg==0.6.0 tqdm==4.67.3

# docker build -t mandelbrot-rocm -f docker/Dockerfile.rocm .
